#!/usr/bin/env python3
"""
generate-compat.py — regenerate keil-compat.h.

Every candidate is checked against what SDCC's own headers already declare and
dropped if it is a duplicate, because SDCC treats a second declaration of an
SFR as an error, not a redefinition. Generating rather than hand-maintaining
means a new SDCC release that adds a register cannot silently break us.

Values are from the STC12C5A60S2 datasheet (2011-07-15); the port bit aliases
are bit-address arithmetic (bit n of a bit-addressable SFR at base B is at
B+n). Nothing is copied from a vendor header.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
import keil2sdcc

SFRS = [
    ("IAP_DATA", 0xC2), ("IAP_ADDRH", 0xC3), ("IAP_ADDRL", 0xC4),
    ("IAP_CMD", 0xC5), ("IAP_TRIG", 0xC6), ("IAP_CONTR", 0xC7),
    ("WDT_CONTR", 0xC1), ("SPSTAT", 0xCE), ("SPCTL", 0xCD), ("SPDAT", 0xCF),
    ("CCAP0L", 0xEA), ("CCAP1L", 0xEB), ("CL", 0xE9), ("CH", 0xF9),
    ("CCAP0H", 0xFA), ("CCAP1H", 0xFB), ("P1ASF", 0x9D), ("P4SW", 0xBB),
    ("AUXR1", 0xA2), ("CCON", 0xD8), ("CMOD", 0xD9),
    ("CCAPM0", 0xDA), ("CCAPM1", 0xDB), ("PCA_PWM0", 0xF2), ("PCA_PWM1", 0xF3),
    ("ADC_CONTR", 0xBC), ("ADC_RES", 0xBD), ("ADC_RESL", 0xBE),
]
PORTS = (("P0", 0x80), ("P1", 0x90), ("P2", 0xA0), ("P3", 0xB0), ("P4", 0xC0))
# Same register, different vendor spelling. IPH2 turns up in 23 of the 26
# vendor headers in the survey; SDCC calls it IP2H, at the same address.
ALIASES = [("IPH2", "IP2H")]

CONSTANTS = [
    ("ADC_POWER", "0x80", "ADC_CONTR bit 7"),
    ("ADC_SPEEDLL", "0x00", "540 clocks per conversion"),
    ("ADC_SPEEDL", "0x20", "360"),
    ("ADC_SPEEDH", "0x40", "180"),
    ("ADC_SPEEDHH", "0x60", "90"),
    ("ADC_FLAG", "0x10", "conversion complete"),
    ("ADC_START", "0x08", "begin a conversion"),
]

# Read SDCC's headers only: scanning the shim would include the very file
# being regenerated, and everything would look like a duplicate of itself.
have_sfr = keil2sdcc.sfr_addresses()
have_bit = keil2sdcc.provided_bits(include_shim=False)

out = [__doc__.strip().splitlines()[0], ""]
out = ["/*", " * keil-compat.h — GENERATED by generate-compat.py, do not hand-edit.",
       " *", " * Declarations Keil's vendor headers provide that SDCC's do not.",
       " * Anything SDCC already declares is omitted: a second declaration of an",
       " * SFR is an error to SDCC, not a redefinition.",
       " *", " * SPDX-License-Identifier: MIT", " */",
       "#ifndef _KEIL_COMPAT_H_", "#define _KEIL_COMPAT_H_", ""]

out.append("/* Port bit aliases in the vendor spelling (P13) beside SDCC's (P1_3). */")
added = 0
for port, base in PORTS:
    for n in range(8):
        name = f"{port}{n}"
        if name in have_bit:
            continue
        out.append(f"__sbit __at (0x{base + n:02X}) {name};")
        added += 1
out.append("")

out.append("/* Registers SDCC's headers do not carry. */")
for name, address in SFRS:
    if name in have_sfr:
        continue
    out.append(f"__sfr __at (0x{address:02X}) {name};")
out.append("")

out.append("/* Vendor-header constants (datasheet 9.2). */")
for name, value, note in CONSTANTS:
    out.append(f"#define {name:<12} {value}   /* {note} */")
out += ["", "/* Same register, different vendor spelling. */"]
for vendor_name, sdcc_name in ALIASES:
    if vendor_name not in have_sfr:
        out.append(f"#define {vendor_name:<12} {sdcc_name}")

out += ["", "/* Older vendor headers spell the IAP registers ISP_*. */"]
for name, _ in SFRS:
    if name.startswith("IAP_"):
        out.append(f"#define ISP_{name[4:]:<8} {name}")
out += ["", "#endif /* _KEIL_COMPAT_H_ */"]

path = pathlib.Path(__file__).parent / "keil-compat.h"
path.write_text("\n".join(out) + "\n")
print(f"wrote {path}: {added} port aliases, "
      f"{sum(1 for n, _ in SFRS if n not in have_sfr)} SFRs, {len(CONSTANTS)} constants")
