/*
 * keil-compat.h — GENERATED by generate-compat.py, do not hand-edit.
 *
 * Declarations Keil's vendor headers provide that SDCC's do not.
 * Anything SDCC already declares is omitted: a second declaration of an
 * SFR is an error to SDCC, not a redefinition.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef _KEIL_COMPAT_H_
#define _KEIL_COMPAT_H_

/* Port bit aliases in the vendor spelling (P13) beside SDCC's (P1_3). */
__sbit __at (0x80) P00;
__sbit __at (0x81) P01;
__sbit __at (0x82) P02;
__sbit __at (0x83) P03;
__sbit __at (0x84) P04;
__sbit __at (0x85) P05;
__sbit __at (0x86) P06;
__sbit __at (0x87) P07;
__sbit __at (0x90) P10;
__sbit __at (0x91) P11;
__sbit __at (0x92) P12;
__sbit __at (0x93) P13;
__sbit __at (0x94) P14;
__sbit __at (0x95) P15;
__sbit __at (0x96) P16;
__sbit __at (0x97) P17;
__sbit __at (0xA0) P20;
__sbit __at (0xA1) P21;
__sbit __at (0xA2) P22;
__sbit __at (0xA3) P23;
__sbit __at (0xA4) P24;
__sbit __at (0xA5) P25;
__sbit __at (0xA6) P26;
__sbit __at (0xA7) P27;
__sbit __at (0xB0) P30;
__sbit __at (0xB1) P31;
__sbit __at (0xB2) P32;
__sbit __at (0xB3) P33;
__sbit __at (0xB4) P34;
__sbit __at (0xB5) P35;
__sbit __at (0xB6) P36;
__sbit __at (0xB7) P37;
__sbit __at (0xC0) P40;
__sbit __at (0xC1) P41;
__sbit __at (0xC2) P42;
__sbit __at (0xC3) P43;
__sbit __at (0xC4) P44;
__sbit __at (0xC5) P45;
__sbit __at (0xC6) P46;
__sbit __at (0xC7) P47;

/* Registers SDCC's headers do not carry. */

/* Vendor-header constants (datasheet 9.2). */
#define ADC_POWER    0x80   /* ADC_CONTR bit 7 */
#define ADC_SPEEDLL  0x00   /* 540 clocks per conversion */
#define ADC_SPEEDL   0x20   /* 360 */
#define ADC_SPEEDH   0x40   /* 180 */
#define ADC_SPEEDHH  0x60   /* 90 */
#define ADC_FLAG     0x10   /* conversion complete */
#define ADC_START    0x08   /* begin a conversion */

/* Older vendor headers spell the IAP registers ISP_*. */
#define ISP_DATA     IAP_DATA
#define ISP_ADDRH    IAP_ADDRH
#define ISP_ADDRL    IAP_ADDRL
#define ISP_CMD      IAP_CMD
#define ISP_TRIG     IAP_TRIG
#define ISP_CONTR    IAP_CONTR

#endif /* _KEIL_COMPAT_H_ */
