/*
 * keil-compat-stc15.h — GENERATED by generate-compat.py, do not hand-edit.
 *
 * Declarations Keil's vendor headers provide that SDCC's do
 * not. Anything the family's SDCC header already declares is
 * omitted: a second declaration of an SFR is an error to SDCC.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef _KEIL_COMPAT_STC15_H_
#define _KEIL_COMPAT_STC15_H_

/* STC15F2K60S2 additions on top of stc12.h (see the generator for
   why the base is stc12.h: the two maps agree except for these).
   P5/P6/P7 are bit-addressable where the address allows. */
__sfr __at (0xD6) T2H;
__sfr __at (0xD7) T2L;
__sfr __at (0x8F) INT_CLKO;
__sfr __at (0xAA) WKTCL;
__sfr __at (0xAB) WKTCH;
__sfr __at (0xE8) P6;
__sfr __at (0xCB) P6M1;
__sfr __at (0xCC) P6M0;
__sfr __at (0xF8) P7;
__sfr __at (0xE1) P7M1;
__sfr __at (0xE2) P7M0;

/* Port bit aliases for the extra ports. */
__sbit __at (0xC8) P50;
__sbit __at (0xC9) P51;
__sbit __at (0xCA) P52;
__sbit __at (0xCB) P53;
__sbit __at (0xCC) P54;
__sbit __at (0xCC) P5_4;
__sbit __at (0xCD) P55;
__sbit __at (0xCD) P5_5;
__sbit __at (0xCE) P56;
__sbit __at (0xCE) P5_6;
__sbit __at (0xCF) P57;
__sbit __at (0xCF) P5_7;
__sbit __at (0xE8) P60;
__sbit __at (0xE8) P6_0;
__sbit __at (0xE9) P61;
__sbit __at (0xE9) P6_1;
__sbit __at (0xEA) P62;
__sbit __at (0xEA) P6_2;
__sbit __at (0xEB) P63;
__sbit __at (0xEB) P6_3;
__sbit __at (0xEC) P64;
__sbit __at (0xEC) P6_4;
__sbit __at (0xED) P65;
__sbit __at (0xED) P6_5;
__sbit __at (0xEE) P66;
__sbit __at (0xEE) P6_6;
__sbit __at (0xEF) P67;
__sbit __at (0xEF) P6_7;
__sbit __at (0xF8) P70;
__sbit __at (0xF8) P7_0;
__sbit __at (0xF9) P71;
__sbit __at (0xF9) P7_1;
__sbit __at (0xFA) P72;
__sbit __at (0xFA) P7_2;
__sbit __at (0xFB) P73;
__sbit __at (0xFB) P7_3;
__sbit __at (0xFC) P74;
__sbit __at (0xFC) P7_4;
__sbit __at (0xFD) P75;
__sbit __at (0xFD) P7_5;
__sbit __at (0xFE) P76;
__sbit __at (0xFE) P7_6;
__sbit __at (0xFF) P77;
__sbit __at (0xFF) P7_7;

#endif /* _KEIL_COMPAT_STC15_H_ */
