/*
 * keil-compat-stc12.h — GENERATED by generate-compat.py, do not hand-edit.
 *
 * Declarations Keil's vendor headers provide that SDCC's do
 * not. Anything the family's SDCC header already declares is
 * omitted: a second declaration of an SFR is an error to SDCC.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef _KEIL_COMPAT_STC12_H_
#define _KEIL_COMPAT_STC12_H_

/* Registers SDCC's stc12.h does not carry (usually none). */

/* P4 lives at 0xC0 on the STC12 (the STC89 puts it at 0xE8). */
__sbit __at (0xC0) P40;
__sbit __at (0xC1) P41;
__sbit __at (0xC2) P42;
__sbit __at (0xC3) P43;
__sbit __at (0xC4) P44;
__sbit __at (0xC5) P45;
__sbit __at (0xC6) P46;
__sbit __at (0xC7) P47;

/* Vendor-header constants (datasheet 9.2 / 7.3). */
#define ADC_POWER    0x80   /* ADC_CONTR bit 7 */
#define ADC_SPEEDLL  0x00   /* 540 clocks per conversion */
#define ADC_SPEEDL   0x20   /* 360 */
#define ADC_SPEEDH   0x40   /* 180 */
#define ADC_SPEEDHH  0x60   /* 90 */
#define ADC_FLAG     0x10   /* conversion complete */
#define ADC_START    0x08   /* begin a conversion */
#define S2SM0        0x80   /* S2CON bit 7 */
#define S2SM1        0x40   /* S2CON bit 6 */
#define S2SM2        0x20   /* S2CON bit 5 */
#define S2REN        0x10   /* S2CON bit 4, receive enable */
#define S2TB8        0x08   /* S2CON bit 3 */
#define S2RB8        0x04   /* S2CON bit 2 */
#define S2TI         0x02   /* S2CON bit 1, transmit flag */
#define S2RI         0x01   /* S2CON bit 0, receive flag */
#define ES2          0x01   /* IE2 bit 0, UART2 interrupt enable */

/* Same register, different vendor spelling. */
#define IPH2         IP2H

/* Older vendor headers spell the IAP registers ISP_*. */
#define ISP_DATA     IAP_DATA
#define ISP_ADDRH    IAP_ADDRH
#define ISP_ADDRL    IAP_ADDRL
#define ISP_CMD      IAP_CMD
#define ISP_TRIG     IAP_TRIG
#define ISP_CONTR    IAP_CONTR

#endif /* _KEIL_COMPAT_STC12_H_ */
