/*
 * keil-compat-8052.h — GENERATED by generate-compat.py, do not hand-edit.
 *
 * Declarations Keil's vendor headers provide that SDCC's do
 * not. Anything the family's SDCC header already declares is
 * omitted: a second declaration of an SFR is an error to SDCC.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef _KEIL_COMPAT_8052_H_
#define _KEIL_COMPAT_8052_H_

/* STC89C5xRC/RD+ extras a reg51/reg52 project expects, restricted
   to addresses that cannot conflict with the STC12 family (see the
   note on STC89_SFRS in the generator). */
__sfr __at (0x8E) AUXR;
__sfr __at (0xA2) AUXR1;
__sfr __at (0xB7) IPH;
__sfr __at (0xC0) XICON;

#endif /* _KEIL_COMPAT_8052_H_ */
