/*
 * keil-compat.h — GENERATED by generate-compat.py, do not hand-edit.
 *
 * Declarations Keil's vendor headers provide that SDCC's do not.
 * Anything SDCC already declares is omitted: a second declaration of an
 * SFR is an error to SDCC, not a redefinition.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef _KEIL_COMPAT_H_
#define _KEIL_COMPAT_H_

/* Port bit aliases in the vendor spelling (P13) beside SDCC's (P1_3). */
__sbit __at (0x80) P00;
__sbit __at (0x81) P01;
__sbit __at (0x82) P02;
__sbit __at (0x83) P03;
__sbit __at (0x84) P04;
__sbit __at (0x85) P05;
__sbit __at (0x86) P06;
__sbit __at (0x87) P07;
__sbit __at (0x90) P10;
__sbit __at (0x91) P11;
__sbit __at (0x92) P12;
__sbit __at (0x93) P13;
__sbit __at (0x94) P14;
__sbit __at (0x95) P15;
__sbit __at (0x96) P16;
__sbit __at (0x97) P17;
__sbit __at (0xA0) P20;
__sbit __at (0xA1) P21;
__sbit __at (0xA2) P22;
__sbit __at (0xA3) P23;
__sbit __at (0xA4) P24;
__sbit __at (0xA5) P25;
__sbit __at (0xA6) P26;
__sbit __at (0xA7) P27;
__sbit __at (0xB0) P30;
__sbit __at (0xB1) P31;
__sbit __at (0xB2) P32;
__sbit __at (0xB3) P33;
__sbit __at (0xB4) P34;
__sbit __at (0xB5) P35;
__sbit __at (0xB6) P36;
__sbit __at (0xB7) P37;
__sbit __at (0xC0) P40;
__sbit __at (0xC1) P41;
__sbit __at (0xC2) P42;
__sbit __at (0xC3) P43;
__sbit __at (0xC4) P44;
__sbit __at (0xC5) P45;
__sbit __at (0xC6) P46;
__sbit __at (0xC7) P47;

/* Registers SDCC's headers do not carry. */

/* Vendor-header constants (datasheet 9.2). */
#define ADC_POWER    0x80   /* ADC_CONTR bit 7 */
#define ADC_SPEEDLL  0x00   /* 540 clocks per conversion */
#define ADC_SPEEDL   0x20   /* 360 */
#define ADC_SPEEDH   0x40   /* 180 */
#define ADC_SPEEDHH  0x60   /* 90 */
#define ADC_FLAG     0x10   /* conversion complete */
#define ADC_START    0x08   /* begin a conversion */
#define S2SM0        0x80   /* S2CON bit 7 */
#define S2SM1        0x40   /* S2CON bit 6 */
#define S2SM2        0x20   /* S2CON bit 5 */
#define S2REN        0x10   /* S2CON bit 4, receive enable */
#define S2TB8        0x08   /* S2CON bit 3 */
#define S2RB8        0x04   /* S2CON bit 2 */
#define S2TI         0x02   /* S2CON bit 1, transmit flag */
#define S2RI         0x01   /* S2CON bit 0, receive flag */
#define ES2          0x01   /* IE2 bit 0, UART2 interrupt enable */

/* Same register, different vendor spelling. */
#define IPH2         IP2H

/* SDCC's math.h carries only the float-suffixed C99 names, and on
   mcs51 double is float anyway. Map the double spellings Keil code
   uses. Function-like on purpose: a variable named exp stays alone. */
#ifndef fabs
#define fabs(x) fabsf(x)
#endif
#ifndef sqrt
#define sqrt(x) sqrtf(x)
#endif
#ifndef sin
#define sin(x) sinf(x)
#endif
#ifndef cos
#define cos(x) cosf(x)
#endif
#ifndef tan
#define tan(x) tanf(x)
#endif
#ifndef asin
#define asin(x) asinf(x)
#endif
#ifndef acos
#define acos(x) acosf(x)
#endif
#ifndef atan
#define atan(x) atanf(x)
#endif
#ifndef sinh
#define sinh(x) sinhf(x)
#endif
#ifndef cosh
#define cosh(x) coshf(x)
#endif
#ifndef tanh
#define tanh(x) tanhf(x)
#endif
#ifndef exp
#define exp(x) expf(x)
#endif
#ifndef log
#define log(x) logf(x)
#endif
#ifndef log10
#define log10(x) log10f(x)
#endif
#ifndef floor
#define floor(x) floorf(x)
#endif
#ifndef ceil
#define ceil(x) ceilf(x)
#endif
#ifndef atan2
#define atan2(a, b) atan2f(a, b)
#endif
#ifndef pow
#define pow(a, b) powf(a, b)
#endif
#ifndef fmod
#define fmod(a, b) fmodf(a, b)
#endif
#ifndef ldexp
#define ldexp(a, b) ldexpf(a, b)
#endif

/* Older vendor headers spell the IAP registers ISP_*. */
#define ISP_DATA     IAP_DATA
#define ISP_ADDRH    IAP_ADDRH
#define ISP_ADDRL    IAP_ADDRL
#define ISP_CMD      IAP_CMD
#define ISP_TRIG     IAP_TRIG
#define ISP_CONTR    IAP_CONTR

#endif /* _KEIL_COMPAT_H_ */
