"""test_avr_symbols — verify AVR two-task compile + symbol extraction.

A two-WHEN-script program exercises the cooperative scheduler:
bw_task0 (blink) and bw_task1 (print). The symbol table must
contain both task function names with yield-state addresses.
"""
import unittest

from app import build_avr, CompileReq, AVR_TARGETS

# Two scripts → cooperative scheduler with bw_task0 + bw_task1.
# Generated by sb3-creator's generateC for an Arduino Uno blink+print.
TWO_TASK_AVR = r"""
/* @bw-begin
 * @bw device arduino-uno
 * @bw clock 16000000
 * @bw pin led1 1 3 output 1
 * @bw script bw_task0 0 stage
 * @bw script bw_task1 1 stage
 * @bw-end */
#include <avr/io.h>
#include <avr/interrupt.h>

#define F_CPU 16000000UL

static volatile unsigned int bw_ms;

ISR(TIMER0_COMPA_vect) { bw_ms++; }

static unsigned int bw_now(void) {
    unsigned int t;
    cli(); t = bw_ms; sei();
    return t;
}

static unsigned int bw_task0_state;
static unsigned int bw_task0_until;

static void bw_task0(void)
{
    switch (bw_task0_state) {
    case 0:
        DDRB |= (1 << PB5);
        bw_task0_state = 1;
    case 1:
        PORTB |= (1 << PB5);
        bw_task0_until = bw_now() + 500;
        bw_task0_state = 2;
    case 2:
        if ((int)(bw_now() - bw_task0_until) < 0) return;
        PORTB &= ~(1 << PB5);
        bw_task0_until = bw_now() + 500;
        bw_task0_state = 3;
    case 3:
        if ((int)(bw_now() - bw_task0_until) < 0) return;
        bw_task0_state = 1;
        return;
    }
    bw_task0_state = 0xFFFF;
}

static unsigned int bw_task1_state;
static unsigned int bw_task1_until;

static void bw_task1(void)
{
    switch (bw_task1_state) {
    case 0:
        bw_task1_state = 1;
    case 1:
        bw_task1_until = bw_now() + 1000;
        bw_task1_state = 2;
    case 2:
        if ((int)(bw_now() - bw_task1_until) < 0) return;
        bw_task1_state = 1;
        return;
    }
    bw_task1_state = 0xFFFF;
}

static void bw_setup(void) {
    /* Timer 0: CTC mode, 1ms tick at 16 MHz / 64 / 250 */
    TCCR0A = (1 << WGM01);
    TCCR0B = (1 << CS01) | (1 << CS00);
    OCR0A = 249;
    TIMSK0 = (1 << OCIE0A);
    sei();
}

int main(void) {
    bw_setup();
    for (;;) {
        bw_task0();
        bw_task1();
    }
}
"""


class TestAvrSymbols(unittest.TestCase):
    def _build(self, **kw):
        req = CompileReq(code=TWO_TASK_AVR, target="atmega328p", **kw)
        return build_avr(req, AVR_TARGETS["atmega328p"], None, 16000000)

    def test_compiles(self):
        r = self._build()
        self.assertTrue(r["success"], r.get("error") or r.get("log", "")[:200])

    def test_hex_nonempty(self):
        r = self._build()
        self.assertGreater(r["bytes"], 0)
        self.assertTrue(r["base64"])

    def test_toolchain_field(self):
        r = self._build()
        self.assertEqual(r["toolchain"], "avr-gcc")
        self.assertEqual(r["mcu"], "atmega328p")

    def test_symbols_contain_tasks(self):
        """The symbol table must find both bw_task functions."""
        r = self._build(symbols=True)
        self.assertTrue(r["success"])
        se = r.get("symbols_error") or ""
        self.assertIsNotNone(r["symbols"],
                             f"symbols is None; symbols_error={se[:100]}")
        tasks = r["symbols"]["scheduler"]["tasks"]
        names = [t["name"] for t in tasks]
        self.assertIn("bw_task0", names, f"bw_task0 not in {names}")
        self.assertIn("bw_task1", names, f"bw_task1 not in {names}")

    def test_symbols_have_yields(self):
        """Each task must have yield entries with state numbers."""
        r = self._build(symbols=True)
        tasks = {t["name"]: t for t in r["symbols"]["scheduler"]["tasks"]}
        for name in ("bw_task0", "bw_task1"):
            self.assertIn(name, tasks, f"{name} not in symbols")
            yields = tasks[name].get("yields", [])
            self.assertGreater(len(yields), 0,
                               f"{name} has no yields: {tasks[name]}")

    def test_disassembly_has_tasks(self):
        r = self._build(disassemble=True)
        self.assertIn("bw_task0", r.get("disassembly", ""))
        self.assertIn("bw_task1", r.get("disassembly", ""))

    def test_listing_present(self):
        r = self._build(disassemble=True)
        self.assertIsNotNone(r.get("listing"))
        self.assertEqual(r["listing"]["format"], "avr-gcc")
        self.assertEqual(r["listing"]["v"], 1)

    def test_hex_starts_with_colon(self):
        """Output is Intel HEX."""
        import base64
        r = self._build()
        content = base64.b64decode(r["base64"]).decode("ascii", errors="replace")
        self.assertTrue(content.startswith(":"), "AVR output must be Intel HEX")


if __name__ == "__main__":
    unittest.main()
