"""test_arm_build — verify the RP2040 compile path end-to-end.

Uses a hand-written freestanding C blink (SIO GPIO25 + TIMER TIMELR delay)
as the oracle. This is NOT generated by generateC; the coordinator writes
the ARM flavor. The test is therefore:
  1. compile succeeds
  2. hex (raw binary) is non-empty
  3. disassembly starts with main at 0x20000000
  4. ELF entry (masked Thumb bit) equals origin
  5. symbols path runs without crashing (symbols_error is expected
     for a single-task program with no bw_taskN)
"""
import unittest

from app import build_arm, CompileReq, ARM_TARGETS

BLINK_C = r"""
#include <stdint.h>

#define SIO_BASE        0xd0000000
#define SIO_GPIO_OUT_SET (*(volatile uint32_t *)(SIO_BASE + 0x14))
#define SIO_GPIO_OUT_CLR (*(volatile uint32_t *)(SIO_BASE + 0x18))
#define SIO_GPIO_OE_SET (*(volatile uint32_t *)(SIO_BASE + 0x24))

#define IO_BANK0_BASE   0x40014000
#define PADS_BANK0_BASE 0x4001c000

#define TIMER_BASE      0x40054000
#define TIMER_TIMELR    (*(volatile uint32_t *)(TIMER_BASE + 0x0c))

static void gpio_init(uint32_t pin) {
    volatile uint32_t *ctrl = (volatile uint32_t *)(IO_BANK0_BASE + 4 + pin * 8);
    *ctrl = 5;
    volatile uint32_t *pad = (volatile uint32_t *)(PADS_BANK0_BASE + 4 + pin * 4);
    *pad = (1 << 6) | (1 << 4);
}

static void gpio_set_dir_out(uint32_t pin) {
    SIO_GPIO_OE_SET = (1u << pin);
}

static void gpio_put(uint32_t pin, int value) {
    if (value) SIO_GPIO_OUT_SET = (1u << pin);
    else       SIO_GPIO_OUT_CLR = (1u << pin);
}

static void delay_ms(uint32_t ms) {
    uint32_t start = TIMER_TIMELR;
    while ((TIMER_TIMELR - start) < ms * 1000u) ;
}

int main(void) {
    gpio_init(25);
    gpio_set_dir_out(25);
    for (;;) {
        gpio_put(25, 1);
        delay_ms(500);
        gpio_put(25, 0);
        delay_ms(500);
    }
}
"""

ORIGIN = 0x20000000


F0_BLINK_C = """
#include <stdint.h>
#define BW_MMIO(a) (*(volatile uint32_t *)(a))
#define RCC_AHBENR   BW_MMIO(0x40021014u)
#define GPIOA_MODER  BW_MMIO(0x48000000u)
#define GPIOA_BSRR   BW_MMIO(0x48000018u)
static void bw_fault(void) { for (;;) { } }
int main(void)
{
    RCC_AHBENR = (1u << 17);
    GPIOA_MODER = 1u;
    for (;;) { GPIOA_BSRR = 1u; GPIOA_BSRR = (1u << 16); }
}
__attribute__((section(".vectors"), used))
const void *vectors[48] = {
    (void *)0x20001000, (void *)main, [3] = (void *)bw_fault
};
"""


class TestArmBuild(unittest.TestCase):
    def test_blink_compiles(self):
        req = CompileReq(code=BLINK_C, target="rp2040")
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertTrue(result["success"], result.get("error"))

    def test_binary_nonempty(self):
        req = CompileReq(code=BLINK_C, target="rp2040")
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertGreater(result["bytes"], 0)

    def test_stm32f030_compiles_with_vectors_first(self):
        # The F0 image is a REAL flash image: SP in word 0 (0x20001000
        # here), reset handler in word 1. A reordered or dropped vector
        # table boots garbage — this asserts the table survived -Os.
        req = CompileReq(code=F0_BLINK_C, target="stm32f030")
        result = build_arm(req, ARM_TARGETS["stm32f030"], None)
        self.assertTrue(result["success"], result.get("error"))
        self.assertEqual(result["origin"], 0x08000000)
        import base64
        blob = base64.b64decode(result["base64"])
        sp = int.from_bytes(blob[0:4], "little")
        reset = int.from_bytes(blob[4:8], "little")
        self.assertEqual(sp, 0x20001000, "word 0 is the initial SP")
        self.assertTrue(0x08000000 <= (reset & ~1) < 0x08004000,
                        f"word 1 is a flash reset handler (0x{reset:08x})")

    def test_entry_at_origin(self):
        req = CompileReq(code=BLINK_C, target="rp2040")
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        entry = result["entry"]
        self.assertIsNotNone(entry)
        self.assertEqual(entry & ~1, ORIGIN,
                         f"entry 0x{entry:08x} != origin 0x{ORIGIN:08x}")

    def test_origin_field(self):
        req = CompileReq(code=BLINK_C, target="rp2040")
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertEqual(result["origin"], ORIGIN)

    def test_toolchain_and_mcu(self):
        req = CompileReq(code=BLINK_C, target="rp2040")
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertEqual(result["toolchain"], "arm-none-eabi-gcc")
        self.assertEqual(result["mcu"], "rp2040")

    def test_disassembly_starts_at_origin(self):
        req = CompileReq(code=BLINK_C, target="rp2040", disassemble=True)
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertIn("20000000 <main>", result["disassembly"])

    def test_symbols_runs_without_crash(self):
        req = CompileReq(code=BLINK_C, target="rp2040", symbols=True)
        result = build_arm(req, ARM_TARGETS["rp2040"], None)
        self.assertTrue(result["success"])
        # Single-task hand-written C: expect symbols_error (no bw_taskN)
        self.assertIsNone(result["symbols"])
        self.assertIn("no bw_taskN", result["symbols_error"])

    def test_unknown_target_rejected(self):
        req = CompileReq(code=BLINK_C, target="rp2040-bad")
        from app import build
        result = build(req)
        self.assertFalse(result["success"])
        self.assertIn("rp2040", result["error"])


if __name__ == "__main__":
    unittest.main()
